spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleboard?useSSL=false&serverTimezone=UTC
    username: simplecrud
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
